### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by sktgintokii** [ierg4210/shop32#1]
Steps:
1. Add to cart
2. Set quantity=-1 at LocalStorage
3. Checkout

See:
500 Internal Server Error

Expected:
Show Invalid count

Possible fix:
check quantity before submission to paypal 

![store32_1](https://cloud.githubusercontent.com/assets/5036163/7492232/529abdb0-f424-11e4-8ef7-7473db4572bd.png)

**Comment by s1155033765** [comment]
Managed to test with your method before, but forgot to see the result in the checkout page...
So yeah, you got that.
It is now fixed.
