### ISSUE TITLE
[P5-4] Cannot checkout more than 1 item

### ISSUE THREAD

**Issue by WindzCUHK** [ierg4210/shop32#2]
## Checkout page hosted at /checkout

Problem:
502 when checkout more than 1 item
![screen shot 2015-05-07 at 3 34 15 pm](https://cloud.githubusercontent.com/assets/6819063/7510445/b88d153c-f4ce-11e4-9285-7512ad993086.png)

**Comment by s1155033765** [comment]
Fixed wrong lines of code before in #1  and didn't check...

Should now be fixed. Please give it a shot!
